### ISSUE TITLE
Schema with no mutations does not generate the 'query' method

### ISSUE THREAD

**Issue by NidhiBedi** [Shopify/graphql_java_gen#19]
My graphQL schema does not have any mutations. When the java classes are generated, it is missing the 'query' method and hence cannot create the GraphQL query.

**Comment by rhysmccaig** [comment]
I just added a PR to address this: https://github.com/Shopify/graphql_java_gen/pull/20

**Comment by dylanahsmith** [comment]
Fixed by https://github.com/Shopify/graphql_java_gen/pull/20
