### ISSUE TITLE
Support serialise nested object as null

### ISSUE THREAD

**Issue by see-mack** [Shopify/graphql_java_gen#27]
The Android client is facing the same problem as iOS. See https://github.com/Shopify/graphql_swift_gen/issues/7

**Comment by wesleyjellis** [comment]
@eapache I could have sworn that we had support for this already somewhere but I can't seem to find us using it

**Comment by eapache** [comment]
I think you're thinking of the other case: telling the difference between a field being missing or having a literal null when returned from the server. I don't think we ever supported it on input objects.
