### ISSUE TITLE
Generated java schema does not import com.shopify.graphql.support.Input

### ISSUE THREAD

**Issue by bhumit** [Shopify/graphql_java_gen#33]
Steps to reproduce

- Generated schema based using `master` branch.
- Upgraded the support version from `0.1.0 -> 0.1.1`
- `com.shopify.graphql.support.Input` is not being imported. 

![image](https://user-images.githubusercontent.com/1700450/31632054-804bd92e-b2b3-11e7-9561-5cae74670b76.png)

**Comment by bhumit** [comment]
I also noticed that the bintray lib was not updated. I unzipped the jar and still don't see `Input` class in the jar.

**Comment by dylanahsmith** [comment]
Looks like version 0.1.1 wasn't tagged after https://github.com/Shopify/graphql_java_gen/pull/25 was merged or uploaded to rubygems.

**Comment by dylanahsmith** [comment]
> Generated schema based using master branch.

Note that if you are going to use the master branch to generate the code, use the master branch for the support package too rather than the one on bintray.

**Comment by bhumit** [comment]
Will you be pushing the tagged version anytime soon?

**Comment by dylanahsmith** [comment]
I wanted to make sure the right version was uploaded.  @DanielJette was commit https://github.com/shopify/graphql_java_gen/commit/1f84b1c8fc13ae25069248ac00314c4176946b0c the one that you uploaded?  That is what it looks like based on the uploaded support-0.1.1-sources.jar, although I would have expected the merge of the version bump to be the one that would be uploaded.

Ideally we should try to get the gradle script to make sure a tagged version is being uploaded.  Even better would be to use [shipit](https://github.com/shopify/shipit-engine) to do the publishing, so we can make sure the rubygem with the same version is also uploaded.

**Comment by DanielJette** [comment]
I'm not sure why I didn't tag the release correctly and I can't recall which version I may have uploaded. 

We haven't been using the bintray/maven version of this library for some time. We're referencing it as a submodule now.

**Comment by dylanahsmith** [comment]
I think I got confused before, I think the version bump PR was the one that got uploaded as the support jar.  I've updated the version for the codegen and pushed a gem build from it to rubygems.
