### ISSUE TITLE
Code generation support not requiring Ruby.

### ISSUE THREAD

**Issue by adam-arold** [Shopify/graphql_java_gen#36]
Is there a way to generate code based on a GraphQL API (like GitHub's API) using this project which **does not** involve Ruby? I think that most Java developers don't want to use Ruby and it is rather cumbersome to use another language's tools to do work with Java.

**Comment by dylanahsmith** [comment]
This project is written in ruby, so you wouldn't be using this project if you didn't want to involve ruby.

Do you mean that you don't want to have to write ruby to use it?  E.g. install an executable that can be configured on the command line

**Comment by adam-arold** [comment]
I don't want to use Ruby at all. I'm writing my project in Java/Kotlin and I found this library which promises to generate Java code. I expected this to be usable from Java.
