### ISSUE TITLE
Errors when field "description" is missing

### ISSUE THREAD

**Issue by babadofar** [Shopify/graphql_java_gen#38]
Using recent versions of graphql-java (7) the ruby generation fails on missing entries for description:

`
ib/ruby/gems/2.4.0/gems/graphql_schema-0.1.6/lib/graphql_schema.rb:53:in fetch': key not found: "description" (KeyError)
        from /lib/ruby/gems/2.4.0/gems/graphql_schema-0.1.6/lib/graphql_schema.rb:53:in description'
`

The description field should perhaps not be mandatory? Earlier versions of the graphql-java library would on missing values for the description field output this:

` "types" : [ {
        "kind" : "OBJECT",
        "name" : "RootQuery",
        "description" : null,...` 

From version 7 onwards, the field is omitted totally if null. 

The specs describe the description field as a nullable type. 
`type GraphQLObjectTypeConfig = {
  name: string;
    ...
  description?: ?string
}`

http://graphql.org/graphql-js/type/#graphqlobjecttype

The error is actually in https://github.com/Shopify/graphql_schema/blob/master/lib/graphql_schema.rb#L53 
` def description
      @hash.fetch('description')
    end
`
It should not assume the description field is always present.

**Comment by dylanahsmith** [comment]
It isn't assuming the description is present, it is assuming that the key is present.  It sounds like your introspection query isn't even requesting the description field.

**Comment by babadofar** [comment]
Hi again, I have traced this back to a commit where we upgraded to Spring Boot 2, of course including quite a few changes.... At least it is not related to changes in graphql-java, we upgraded to version 7 long before this. 

The introspection query did not change, and it includes the description field. 
Will report back here if I figure out what happened 😹 
` 
query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }


  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description

`

**Comment by babadofar** [comment]
Figured it out. It was an issue with ObjectMapper 
objectMapper.setSerializationInclusion(JsonInclude.Include.ALWAYS); fixed it  . Funny this poppped up after spring boot upgrade 2
