### ISSUE TITLE
TopLevelResponse should provide API to be constructed from String

### ISSUE THREAD

**Issue by sav007** [Shopify/graphql_java_gen#4]
It would be nice `com.shopify.graphql.support.TopLevelResponse` to have constructor that accepts json string as parameter, and uses `com.google.gson.JsonParser` internally. So from user perspective no need to know that `Gson` is used internally and API will be simplified:

```
graphQlResponse = new TopLevelResponse(response.body().string());
```

**Comment by dylanahsmith** [comment]
I don't understand the problem.  Currently you don't need to know that Gson is being used internally using the example from the README for parsing a response:

```java
ExampleSchema.QueryResponse response = ExampleSchema.QueryResponse.fromJson(responseJson);
```

so from a typical user's perspective they shouldn't be trying to construct a generic TopLevelResponse object, they should be constructing a query or mutation response object that corresponds to the query that was sent.

**Comment by sav007** [comment]
@dylanahsmith 

see https://github.com/Shopify/graphql_java_gen/blob/master/support/src/main/java/com/shopify/graphql/support/TopLevelResponse.java#L18

Argument for constructor: `com.google.gson.JsonObject`
Proposal to change it to String

**Comment by sav007** [comment]
@dylanahsmith oh sorry my bad

I didn't pay attention that this is generated
```
ExampleSchema.QueryResponse response = ExampleSchema.QueryResponse.fromJson(responseJson);
```

Thanks, this issue is not valid anymore
