### ISSUE TITLE
0.2.0 Release?

### ISSUE THREAD

**Issue by ryankazokas** [Shopify/graphql_java_gen#50]
I am trying to use the newest version of this according to the readme. I would benefit from being able to use the 'save_granular', but when i attempt to install the 0.2.0 gem, it's not able to. Is there a plan to release a 0.2.0 gem version of this anytime soon? or is this a dead repo?

`Fetching gem metadata from https://rubygems.org/..
Could not find gem 'graphql_java_gen (= 0.2.0) x64-mingw32' in any of the gem
sources listed in your Gemfile.`

**Comment by ryankazokas** [comment]
Nevermind, i see this is being managed through the buy sdk through a submodule:
https://github.com/Shopify/mobile-buy-sdk-android

Is there a way for you to update docs to show how to include this in your own project via a submodule? I basically just want the java graphql gen stuff instead of the entire buy sdk.

**Comment by dylanahsmith** [comment]
The steps are basically to use a git submodule (e.g. `git submodule https://github.com/Shopify/graphql_java_gen.git`) and to reference the submodule directory from the Gemfile (e.g. `gem 'graphql_java_gen', path: 'graphql_java_gen'`) and the gradle build configuration (looks like mobile-buy-sdk-android does this in [build.gradle](https://github.com/Shopify/mobile-buy-sdk-android/blob/31af98fac15a8c81563b3266f85cab85b953ef0d/MobileBuy/buy3/build.gradle#L26-L28) and [settings.gradle](https://github.com/Shopify/mobile-buy-sdk-android/blob/31af98fac15a8c81563b3266f85cab85b953ef0d/MobileBuy/settings.gradle#L2)).

**Comment by ryankazokas** [comment]
Awesome, yeah that's what im' trying right now. I initally thought this was used through jcenter as the read me states. Feel free to close this.

**Comment by dylanahsmith** [comment]
It can be used through jcenter and rubygems if you want the last release.

However, if you want to use the latest commit on master that hasn't been released, then using git submodules allows you to do that.

**Comment by dylanahsmith** [comment]
Made a 0.2.0 release
