### ISSUE TITLE
Support Java library 0.2.0

### ISSUE THREAD

**Issue by sale87** [Shopify/graphql_java_gen#55]
Hello,

first of all thank you very much for your work and open sourcing this tool, it is of great help!

I tried using generated GraphQL library in my project and noticed that version 0.2.0 (com.shopify.graphql.support:support:0.2.0) of Java support library is not yet published to jCenter (latest version available there is 0.1.1).

I have manually built lib from repo support folder and included in my project, but I thought that you would like to know this and  publish support library when you have time.

Once again, thank you very much for your work!

All best,
Sasa

**Comment by dylanahsmith** [comment]
Doesn't https://bintray.com/shopify/shopify-java/graphql-support/0.2.0 indicate that it is published?

**Comment by sale87** [comment]
Yes, my bad, I was looking on https://mvnrepository.com/artifact/com.shopify.graphql.support/support.

Thank you very much!

All best,
Sasa
