### ISSUE TITLE
Generation tool should annotate deprecated fields with @Deprecated.

### ISSUE THREAD

**Issue by sav007** [Shopify/graphql_java_gen#6]
GraphQL schema provides `isDeprecated` flag to deprecate fields.
Generation tool should annotate accessor methods to these fields with @Deprecated annotation.
Would be nice even provide the reason that specified in `deprecationReason`

**Comment by dylanahsmith** [comment]
Yes, it would be nice to optional provide support for this.  This is basically the approach we took for swift using attributes.

The problem I ran into with trying to surface this information for java was that our mobile-shopify project was already using a bunch of deprecated android fields to support older android versions, so just marking methods as deprecated wouldn't make their use obvious enough to make sure all usage of deprecated fields are removed.

So if you are going to add support for deprecation attributions, then make sure you can enable a lint check that allows deprecated fields usage to be noticed and removed quickly after they are deprecated.
