### ISSUE TITLE
Split generated code into separate files

### ISSUE THREAD

**Issue by dylanahsmith** [Shopify/graphql_java_gen#8]
The output for the code generator can get quite large, which also makes it harder to find things in.

I think it would be nicer to write to separate files for the different GraphQL types.

**Comment by AustinLMayes** [comment]
Any news on this?

**Comment by AustinLMayes** [comment]
In case anyone wanted to see this in action:
https://github.com/Avicus/graphql_java_gen

**Comment by dylanahsmith** [comment]
Why didn't you open a PR?

**Comment by dylanahsmith** [comment]
Implemented in https://github.com/Shopify/graphql_java_gen/pull/35
